#!/bin/bash 

# This hook is triggered after the bind mount is added as a result of a
# connection for edgex-secretstore-token content interface.
#
# The connection can happen before or after edgex-ekuiper:
#
#   BEFORE when a provider snap (from the same publisher) is installed before
#   the edgex-ekuiper snap and the content interface is auto-connected.
#
#   AFTER, when:
#     1. A provider snap (from the same publisher) is installed after the
#        edgex-ekuiper snap and the content interface is auto-connected.
#     2. A connection to an external provider snap is made manually after the
#        installation of the edgex-ekuiper snap.

logger "edgex-ekuiper: connect-slot-edgex-secretstore-token: connected"

